import Head from 'next/head';
import { useState } from 'react';
import { phoneAuth } from '../helper/utils';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [value, setValue] = useState({
    phone: '',
    auth_token: '',
  });

  const handleChange = (e) => {
    setValue({ ...value, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    phoneAuth(value.phone)
      .then((res) => console.log(res))
      .catch((e) => console.log(e));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Appwrite | Twilio Auth</title>
        <meta name='description' content='Generated by appwrite twilio aauth' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex justify-center items-center h-screen'>
        <div className='rounded-xl w-96 p-7 shadow-xl'>
          <h1 className='text-xl font-bold mb-6 text-indigo-900 text-center'>
            Appwrite | Twilio Auth
          </h1>
          <form onSubmit={handleSubmit}>
            <fieldset className='mb-4'>
              <label className='text-sm block mb-2'>Phone Number</label>
              <input
                className='h-10 border w-full rounded border-gray-400'
                required
                type='tel'
                name='phone'
                onChange={handleChange}
              />
            </fieldset>
            <button className='bg-indigo-900 w-full h-10 rounded font-semibold text-white hover:bg-indigo-700'>
              Submit
            </button>
          </form>
        </div>
      </main>
    </div>
  );
}
